/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TvRemoteRouteImport } from './routes/tv-remote'
import { Route as SettingsUsersRouteImport } from './routes/settings-users'
import { Route as SettingsSafetyRouteImport } from './routes/settings-safety'
import { Route as SettingsNetworkRouteImport } from './routes/settings-network'
import { Route as SettingsGatewaysRouteImport } from './routes/settings-gateways'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SelectDeviceRouteImport } from './routes/select-device'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as RemotesRouteImport } from './routes/remotes'
import { Route as FridgeRemoteRouteImport } from './routes/fridge-remote'
import { Route as EnergyRouteImport } from './routes/energy'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as ConsoleRemoteRouteImport } from './routes/console-remote'
import { Route as CameraRouteImport } from './routes/camera'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as AudioRemoteRouteImport } from './routes/audio-remote'
import { Route as AllDevicesRouteImport } from './routes/all-devices'
import { Route as AddRoomRouteImport } from './routes/add-room'
import { Route as AddDeviceRouteImport } from './routes/add-device'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomRoomIdRouteImport } from './routes/room.$roomId'
import { Route as DeviceDeviceIdRouteImport } from './routes/device.$deviceId'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const TvRemoteRoute = TvRemoteRouteImport.update({
  id: '/tv-remote',
  path: '/tv-remote',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/settings-users',
  path: '/settings-users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSafetyRoute = SettingsSafetyRouteImport.update({
  id: '/settings-safety',
  path: '/settings-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNetworkRoute = SettingsNetworkRouteImport.update({
  id: '/settings-network',
  path: '/settings-network',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsGatewaysRoute = SettingsGatewaysRouteImport.update({
  id: '/settings-gateways',
  path: '/settings-gateways',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectDeviceRoute = SelectDeviceRouteImport.update({
  id: '/select-device',
  path: '/select-device',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const RemotesRoute = RemotesRouteImport.update({
  id: '/remotes',
  path: '/remotes',
  getParentRoute: () => rootRouteImport,
} as any)
const FridgeRemoteRoute = FridgeRemoteRouteImport.update({
  id: '/fridge-remote',
  path: '/fridge-remote',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergyRoute = EnergyRouteImport.update({
  id: '/energy',
  path: '/energy',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRemoteRoute = ConsoleRemoteRouteImport.update({
  id: '/console-remote',
  path: '/console-remote',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraRoute = CameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioRemoteRoute = AudioRemoteRouteImport.update({
  id: '/audio-remote',
  path: '/audio-remote',
  getParentRoute: () => rootRouteImport,
} as any)
const AllDevicesRoute = AllDevicesRouteImport.update({
  id: '/all-devices',
  path: '/all-devices',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoomRoute = AddRoomRouteImport.update({
  id: '/add-room',
  path: '/add-room',
  getParentRoute: () => rootRouteImport,
} as any)
const AddDeviceRoute = AddDeviceRouteImport.update({
  id: '/add-device',
  path: '/add-device',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceDeviceIdRoute = DeviceDeviceIdRouteImport.update({
  id: '/device/$deviceId',
  path: '/device/$deviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/add-device': typeof AddDeviceRoute
  '/add-room': typeof AddRoomRoute
  '/all-devices': typeof AllDevicesRoute
  '/audio-remote': typeof AudioRemoteRoute
  '/automations': typeof AutomationsRoute
  '/camera': typeof CameraRoute
  '/console-remote': typeof ConsoleRemoteRoute
  '/devices': typeof DevicesRoute
  '/energy': typeof EnergyRoute
  '/fridge-remote': typeof FridgeRemoteRoute
  '/remotes': typeof RemotesRoute
  '/rooms': typeof RoomsRoute
  '/select-device': typeof SelectDeviceRoute
  '/settings': typeof SettingsRoute
  '/settings-gateways': typeof SettingsGatewaysRoute
  '/settings-network': typeof SettingsNetworkRoute
  '/settings-safety': typeof SettingsSafetyRoute
  '/settings-users': typeof SettingsUsersRoute
  '/tv-remote': typeof TvRemoteRoute
  '/api/chat': typeof ApiChatRoute
  '/device/$deviceId': typeof DeviceDeviceIdRoute
  '/room/$roomId': typeof RoomRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/add-device': typeof AddDeviceRoute
  '/add-room': typeof AddRoomRoute
  '/all-devices': typeof AllDevicesRoute
  '/audio-remote': typeof AudioRemoteRoute
  '/automations': typeof AutomationsRoute
  '/camera': typeof CameraRoute
  '/console-remote': typeof ConsoleRemoteRoute
  '/devices': typeof DevicesRoute
  '/energy': typeof EnergyRoute
  '/fridge-remote': typeof FridgeRemoteRoute
  '/remotes': typeof RemotesRoute
  '/rooms': typeof RoomsRoute
  '/select-device': typeof SelectDeviceRoute
  '/settings': typeof SettingsRoute
  '/settings-gateways': typeof SettingsGatewaysRoute
  '/settings-network': typeof SettingsNetworkRoute
  '/settings-safety': typeof SettingsSafetyRoute
  '/settings-users': typeof SettingsUsersRoute
  '/tv-remote': typeof TvRemoteRoute
  '/api/chat': typeof ApiChatRoute
  '/device/$deviceId': typeof DeviceDeviceIdRoute
  '/room/$roomId': typeof RoomRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/add-device': typeof AddDeviceRoute
  '/add-room': typeof AddRoomRoute
  '/all-devices': typeof AllDevicesRoute
  '/audio-remote': typeof AudioRemoteRoute
  '/automations': typeof AutomationsRoute
  '/camera': typeof CameraRoute
  '/console-remote': typeof ConsoleRemoteRoute
  '/devices': typeof DevicesRoute
  '/energy': typeof EnergyRoute
  '/fridge-remote': typeof FridgeRemoteRoute
  '/remotes': typeof RemotesRoute
  '/rooms': typeof RoomsRoute
  '/select-device': typeof SelectDeviceRoute
  '/settings': typeof SettingsRoute
  '/settings-gateways': typeof SettingsGatewaysRoute
  '/settings-network': typeof SettingsNetworkRoute
  '/settings-safety': typeof SettingsSafetyRoute
  '/settings-users': typeof SettingsUsersRoute
  '/tv-remote': typeof TvRemoteRoute
  '/api/chat': typeof ApiChatRoute
  '/device/$deviceId': typeof DeviceDeviceIdRoute
  '/room/$roomId': typeof RoomRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/add-device'
    | '/add-room'
    | '/all-devices'
    | '/audio-remote'
    | '/automations'
    | '/camera'
    | '/console-remote'
    | '/devices'
    | '/energy'
    | '/fridge-remote'
    | '/remotes'
    | '/rooms'
    | '/select-device'
    | '/settings'
    | '/settings-gateways'
    | '/settings-network'
    | '/settings-safety'
    | '/settings-users'
    | '/tv-remote'
    | '/api/chat'
    | '/device/$deviceId'
    | '/room/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/add-device'
    | '/add-room'
    | '/all-devices'
    | '/audio-remote'
    | '/automations'
    | '/camera'
    | '/console-remote'
    | '/devices'
    | '/energy'
    | '/fridge-remote'
    | '/remotes'
    | '/rooms'
    | '/select-device'
    | '/settings'
    | '/settings-gateways'
    | '/settings-network'
    | '/settings-safety'
    | '/settings-users'
    | '/tv-remote'
    | '/api/chat'
    | '/device/$deviceId'
    | '/room/$roomId'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/add-device'
    | '/add-room'
    | '/all-devices'
    | '/audio-remote'
    | '/automations'
    | '/camera'
    | '/console-remote'
    | '/devices'
    | '/energy'
    | '/fridge-remote'
    | '/remotes'
    | '/rooms'
    | '/select-device'
    | '/settings'
    | '/settings-gateways'
    | '/settings-network'
    | '/settings-safety'
    | '/settings-users'
    | '/tv-remote'
    | '/api/chat'
    | '/device/$deviceId'
    | '/room/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AddDeviceRoute: typeof AddDeviceRoute
  AddRoomRoute: typeof AddRoomRoute
  AllDevicesRoute: typeof AllDevicesRoute
  AudioRemoteRoute: typeof AudioRemoteRoute
  AutomationsRoute: typeof AutomationsRoute
  CameraRoute: typeof CameraRoute
  ConsoleRemoteRoute: typeof ConsoleRemoteRoute
  DevicesRoute: typeof DevicesRoute
  EnergyRoute: typeof EnergyRoute
  FridgeRemoteRoute: typeof FridgeRemoteRoute
  RemotesRoute: typeof RemotesRoute
  RoomsRoute: typeof RoomsRoute
  SelectDeviceRoute: typeof SelectDeviceRoute
  SettingsRoute: typeof SettingsRoute
  SettingsGatewaysRoute: typeof SettingsGatewaysRoute
  SettingsNetworkRoute: typeof SettingsNetworkRoute
  SettingsSafetyRoute: typeof SettingsSafetyRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  TvRemoteRoute: typeof TvRemoteRoute
  ApiChatRoute: typeof ApiChatRoute
  DeviceDeviceIdRoute: typeof DeviceDeviceIdRoute
  RoomRoomIdRoute: typeof RoomRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tv-remote': {
      id: '/tv-remote'
      path: '/tv-remote'
      fullPath: '/tv-remote'
      preLoaderRoute: typeof TvRemoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-users': {
      id: '/settings-users'
      path: '/settings-users'
      fullPath: '/settings-users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-safety': {
      id: '/settings-safety'
      path: '/settings-safety'
      fullPath: '/settings-safety'
      preLoaderRoute: typeof SettingsSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-network': {
      id: '/settings-network'
      path: '/settings-network'
      fullPath: '/settings-network'
      preLoaderRoute: typeof SettingsNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-gateways': {
      id: '/settings-gateways'
      path: '/settings-gateways'
      fullPath: '/settings-gateways'
      preLoaderRoute: typeof SettingsGatewaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-device': {
      id: '/select-device'
      path: '/select-device'
      fullPath: '/select-device'
      preLoaderRoute: typeof SelectDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remotes': {
      id: '/remotes'
      path: '/remotes'
      fullPath: '/remotes'
      preLoaderRoute: typeof RemotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fridge-remote': {
      id: '/fridge-remote'
      path: '/fridge-remote'
      fullPath: '/fridge-remote'
      preLoaderRoute: typeof FridgeRemoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energy': {
      id: '/energy'
      path: '/energy'
      fullPath: '/energy'
      preLoaderRoute: typeof EnergyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console-remote': {
      id: '/console-remote'
      path: '/console-remote'
      fullPath: '/console-remote'
      preLoaderRoute: typeof ConsoleRemoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera': {
      id: '/camera'
      path: '/camera'
      fullPath: '/camera'
      preLoaderRoute: typeof CameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio-remote': {
      id: '/audio-remote'
      path: '/audio-remote'
      fullPath: '/audio-remote'
      preLoaderRoute: typeof AudioRemoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-devices': {
      id: '/all-devices'
      path: '/all-devices'
      fullPath: '/all-devices'
      preLoaderRoute: typeof AllDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-room': {
      id: '/add-room'
      path: '/add-room'
      fullPath: '/add-room'
      preLoaderRoute: typeof AddRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-device': {
      id: '/add-device'
      path: '/add-device'
      fullPath: '/add-device'
      preLoaderRoute: typeof AddDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/$deviceId': {
      id: '/device/$deviceId'
      path: '/device/$deviceId'
      fullPath: '/device/$deviceId'
      preLoaderRoute: typeof DeviceDeviceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AddDeviceRoute: AddDeviceRoute,
  AddRoomRoute: AddRoomRoute,
  AllDevicesRoute: AllDevicesRoute,
  AudioRemoteRoute: AudioRemoteRoute,
  AutomationsRoute: AutomationsRoute,
  CameraRoute: CameraRoute,
  ConsoleRemoteRoute: ConsoleRemoteRoute,
  DevicesRoute: DevicesRoute,
  EnergyRoute: EnergyRoute,
  FridgeRemoteRoute: FridgeRemoteRoute,
  RemotesRoute: RemotesRoute,
  RoomsRoute: RoomsRoute,
  SelectDeviceRoute: SelectDeviceRoute,
  SettingsRoute: SettingsRoute,
  SettingsGatewaysRoute: SettingsGatewaysRoute,
  SettingsNetworkRoute: SettingsNetworkRoute,
  SettingsSafetyRoute: SettingsSafetyRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  TvRemoteRoute: TvRemoteRoute,
  ApiChatRoute: ApiChatRoute,
  DeviceDeviceIdRoute: DeviceDeviceIdRoute,
  RoomRoomIdRoute: RoomRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
